spring:
  application:
    name: ms-security
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      enabled: true
  profiles:
    active: default

logging:
  level:
    org.springframework.cloud.config.client: TRACE